apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-helloworld-one-app2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: aks-helloworld-one-app2
  template:
    metadata:
      labels:
        app: aks-helloworld-one-app2
    spec:
      containers:
      - name: aks-helloworld-one-app2
        image: neilpeterson/aks-helloworld:v1
        ports:
        - containerPort: 80
        env:
        - name: TITLE
          value: "Welcome to Azure Arc Webinar From App2"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-helloworld-one-app2
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aks-helloworld-one-app2
